# Generated by Django 5.2.8 on 2025-11-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='img',
            field=models.ImageField(blank=True, upload_to='clothes/'),
        ),
    ]
