# Generated by Django 5.2.8 on 2025-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_roupa_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roupa',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roupa',
            name='price_promo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roupa',
            name='unit',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
