# Generated by Django 5.2.8 on 2025-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roupa_is_promo_roupa_price_roupa_price_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='price',
            field=models.FloatField(),
        ),
    ]
