# Generated by Django 5.2.8 on 2025-11-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_roupa_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('Img', models.ImageField(blank=True, upload_to='clothes_view/')),
                ('Unit', models.PositiveIntegerField(default=0)),
                ('Price', models.FloatField()),
                ('Price_promo', models.FloatField(blank=True, null=True)),
                ('Is_promo', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClotheImage',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Img', models.ImageField(blank=True, upload_to='clothes/')),
                ('Fk_clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clothe')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('Size', models.CharField(max_length=4)),
                ('Specification', models.TextField()),
                ('Mark', models.CharField()),
                ('Fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('Fk_clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clothe')),
            ],
        ),
        migrations.DeleteModel(
            name='Roupa',
        ),
    ]
