# Generated by Django 5.2.8 on 2025-11-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_clothe_clotheimage_description_delete_roupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clotheimage',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
